### ISSUE TITLE
Dockerfile rest service

### ISSUE THREAD

**Issue by inodb** [Ensembl/ensembl-rest#245]
For cBioPortal (http://www.cbioportal.org/) we are using Genome Nexus (http://genomenexus.org/#/home) to annotate our date before importing, which talks to the Ensembl REST endpoint (http://grch37.rest.ensembl.org/). In order to not overload the Ensembl service it would be nice if there was a docker file for the rest service, so we can run our own. I'm happy to make this and send a PR to ensembl-rest repo - just wondering if there are any reasons other than time constraints why there isn't one already. Thank you!

**Comment by nerdstrike** [comment]
@inodb Thanks for your interest in the REST API. I believe you've had a response elsewhere, so I'd like to close this issue. Our host institution does not currently support Docker so we would struggle to keep a Docker image fresh. There are also issues attached to the deployment of an Ensembl MySQL server, with 2 TB of data, plus another 200 GB or so of cache files. In future we are intending to make ensembl-rest less monolithic which should help your cause as well as ours.

**Comment by Alex-Willenbrink** [comment]
inodb, did you ever make that dockerfile?

**Comment by inodb** [comment]
@Alex-Willenbrink unf not - i actually ended up creating a lightweight java spring boot wrapper around the vep perl script. I am really only interested in vep results so the other endpoints aren't as important of our purpose. It can be found here:

https://github.com/genome-nexus/genome-nexus-vep

Getting cache initialized is the same as using normal vep dockerfile:
https://useast.ensembl.org/info/docs/tools/vep/script/vep_download.html

**Comment by lairdm** [comment]
As @nerdstrike has said, this has been addressed elsewhere and an alternative solution has been found. Closing this ticket.
