### ISSUE TITLE
Configure local ensembl-rest for GRCh37

### ISSUE THREAD

**Issue by bwalsh** [Ensembl/ensembl-rest#258]
Hello, thank you for a great product.

I've been using:
* https://grch37.rest.ensembl.org/vep
* https://grch37.rest.ensembl.org/lookup/id/
With no problem.

However, in order to improve response times, I was hoping to instantiate it locally.
I've brought up the server following instructions at https://github.com/Ensembl/ensembl-rest/wiki/REST-Installation-and-Development

Is there a way to configure GRCh37 access?  I do see the following in ensembl_rest.conf, but am unclear as to their effect.

```
    from_coord_system=GRCh37
    to_coord_system=GRCh38
```

**Comment by bwalsh** [comment]
Found a solution.  Leaving this here in case it helps someone in the future.

In `ensembl_rest.conf`
set db connection to:

```
  host = ensembldb.ensembl.org
  port = 3337
  user = anonymous
```

 Feel free to close this issue.

**Comment by magaliruffier** [comment]
Thanks for your input and apologies for the lack of reply.
You are correct, you can set the db connection in the ensembl_rest.conf to point to the server of your choice. If you want to further improve the response time, you could even host your local server to reduce latency, and point to it by updating the same section in the configuration file.
Please do not hesitate to contact us again if you have further questions, we are always looking for feedback.
