### ISSUE TITLE
Potential issue with LD functions

### ISSUE THREAD

**Issue by hsinyen** [Ensembl/ensembl-rest#276]
Thank you for this wonderful API, it's been very useful!
I am finding that it seems to "miss" some SNPs when I use _GET ld/:species/:id/:population_nam_e in humans. 

For example,  rs492400 and rs600057 are 100k bps apart and have high ld (r2=1.0, d_prime= 1.0 in CEU). However, when I try to run  _GET ld/:species/:id/:population_name_ on rs492400, rs600057 never pops up in the result, regardless of which 1000G population I use. It also doesn't work if I try to run the function on rs600057. 

I'd really appreciate your help!

**Comment by at7** [comment]
Hi @hsinyen, the C script which computes the LD values overwrites the window size and sets it to 100kb. I need to update the documentation of the endpoint accordingly. We used to see performance problems with an allowed window size of 500kb. If you need a larger window size than 100kb I recommend you try our perl [script](https://github.com/Ensembl/ensembl-variation/tree/release/93/tools/linkage_disequilibrium) for computing LD. Thank you for reporting the error. If you have any questions for example regarding the LD script please contact dev@ensembl.org or our [helpdesk](https://www.ensembl.org/Help/Contact) team.

**Comment by nerdstrike** [comment]
Ensembl does not use Github to track bug reports. I will close this issue. If Anja has not resolved your problem, please contact us through helpdesk@ensembl.org or dev@ensembl.org
