### ISSUE TITLE
GET sequence: PB downloading

### ISSUE THREAD

**Issue by leapicard** [Ensembl/ensembl-rest#297]
Hello,

I am using Ensembl-rest to download sequences using their CCDS ids.
However, for some of them, it is impossible to get the sequences, because the "Content-Type text/html is not supported."
The script (very simple & straightforward) works for the vast majority of the sequences, and I can't understand why I run into this problem.
Would you have any idea?

Best,
Lea

**Comment by nerdstrike** [comment]
Hi Lea,

The "content-type not supported" is a known bug and the fix will roll out in release 95. The real error is hidden behind the error for sending the error to the user...

Most likely you are asking for IDs, so I recommend you contact us via helpdesk@ensembl.org , as the error is likely not specific to Ensembl REST. Be sure to include some example CCDS IDs that are failing for you.

Ensembl uses issue tracking elsewhere than Github, so I will now close this issue. Thank you for reporting your problem.
