### ISSUE TITLE
Is it possible to host stand alone instances of VEP, and not the whole REST server? Only interested in the VEP REST API

### ISSUE THREAD

**Issue by nmousavi** [Ensembl/ensembl-rest#311]
Asking the same question as in 

https://github.com/Ensembl/ensembl-rest-deploy/issues/6

**Comment by nerdstrike** [comment]
Running VEP REST in isolation would require fairly aggressive cutting away of parts of the codebase. Modular functionality is in the design for our second iteration of this product, but we are not there yet. Contact helpdesk@ensembl.org if you would like further discuss your issue.
