### ISSUE TITLE
Database error when trying to access data

### ISSUE THREAD

**Issue by piotr-gawron** [Ensembl/ensembl-rest#366]
When I try to access data with identifier (I'm not completely sure if it's existing identifier) I get a database error (or 504 Gateway Time-out).

Here is example of the url that produce error:
https://rest.ensembl.org/xrefs/id/ENSG00000000001?content-type=application/json

And here is the error message that I got:

{"error":"Could not connect to database bacteria_22_collection_core_44_97_1 as user ensro using [DBI:mysql:database=bacteria_22_collection_core_44_97_1;host=hh-mysql-eg-rest-web;port=4598] as a locator:DBI connect('database=bacteria_22_collection_core_44_97_1;host=hh-mysql-eg-rest-web;port=4598','ensro',...) failed: Can't connect to MySQL server on 'hh-mysql-eg-rest-web' (99) at /nfs/public/release/ensweb/live/rest/www_97/ensembl/modules/Bio/EnsEMBL/DBSQL/DBConnection.pm line 260."}

**Comment by nicklangridge** [comment]
Hi @piotr-gawron, thanks for reporting this. A configuration error meant that the server was not responding correctly when a ID not present in the database was requested. It's fixed now.
