### ISSUE TITLE
Really long `NNNNN` entry for `allele_string` for some deletions

### ISSUE THREAD

**Issue by inodb** [Ensembl/ensembl-rest#397]
E.g.

http://grch37.rest.ensembl.org/vep/human/hgvs/11:g.148657042delT?content-type=application/json

**Comment by nerdstrike** [comment]
@aparton can you explain the behaviour? This might be in VEP itself rather than REST

**Comment by aparton** [comment]
Hi,

I’ve had a look at this issue this morning, REST VEP behaves in this way when it’s given a deletion that occurs after the expected end of the chromosome. 

It’s not clean, so we’ll take a look at getting a fix into release 99.

Thanks,
Andrew

**Comment by inodb** [comment]
I see - thanks for the quick reply @nerdstrike and @aparton !

**Comment by nerdstrike** [comment]
This fix has been pushed back by more critical bug-fixes taking precedence. Until further notice, assume release 100.
