### ISSUE TITLE
API is down

### ISSUE THREAD

**Issue by eweitz** [Ensembl/ensembl-rest#461]
Hi Ensembl REST team -- it looks like the API is down.  I get 500 internal server errors for:

* https://rest.ensembl.org/
* https://rest.ensembl.org/homology/id/ENSG00000051180?&format=condensed&type=paralogues&target_taxon=9606&content-type=application/json

Screenshot of latter:
<img width="1440" alt="Ensembl_REST_API_500_error_for_homology_id_GET_2020-10-13T2245-0400" src="https://user-images.githubusercontent.com/1334561/95938091-29fbcf00-0da7-11eb-8eb7-ca9c8a1f2ae5.png">

I occasionally get a 200 OK for requests like the latter after a long wait (15+ seconds), but the vast majority of responses are 500 errors.  I first noticed instability around 20:00 UTC (4:00 PM EST) on 2020-10-13.

Ensembl REST API is immensely useful -- I use it to power [Ideogram for Related Genes](https://eweitz.github.io/ideogram/related-genes?q=RAD51).  Any idea when the API will be back up?

**Comment by ens-bwalts** [comment]
Hello

Apologies for the service disruption and thank you for bringing this to our attention. We have restarted the REST machines, and it looks like they are operating normally.

**Comment by eweitz** [comment]
Confirmed, thank you!
