### ISSUE TITLE
Mastermind plugin not working

### ISSUE THREAD

**Issue by FlorianErger** [Ensembl/ensembl-rest#483]
Hello,

I have been trying to get Mastermind annotations through the REST API, but in my tests the parameter seems to be ineffectual and no Mastermind annotation is returned. The Mastermind plugin works in the web interface as expected, so I suspect an error on my part, or an issue with the REST API. Python request to replicate:

```
from requests import get

server = "https://grch37.rest.ensembl.org/vep/human/hgvs/"
hgvs_var = "6:g.51947999G>A"  # PKHD1 p.T36M, well-known pathogenic variant, annotated with the correct Mastermind link on the VEP web interface as expected - Mastermind links 94 publications for this variant
headers = {"Content-Type": "application/json", "Accept": "application/json"}
params = {"Mastermind": 1}

res_json = get(server + hgvs_var, headers=headers, params=params).json()
```

The returned json contains no Mastermind data. From the documentation it is not clear to me what the problem could be.

Appreciate any help!
Best,
Florian

**Comment by mira13** [comment]
Hello Florian, 

Thanks for your feedback,
I will check this endpoint and come back to you soon

Kind regards,
Mira

**Comment by FlorianErger** [comment]
Dear Mira,

thanks for having a look. Were you able to reproduce the problem?

Best,
Florian

**Comment by mira13** [comment]
Hello, Florian, 

Sorry for the late response, 
the issue turned out web team deployment issue, 
Diana Lemos discussed it with web team and they resolved, so now endpoint works correct with grch37 :

 http://grch37.rest.ensembl.org/vep/human/hgvs/6:g.51947999G%3EA?content-type=application/json&Mastermind=1


Cheers,
Mira

**Comment by FlorianErger** [comment]
Sorry to reopen this, but do you happen to know how the web team fixed the issue? I have set up a local ensembl-rest server and while other VEP-plugins work well (CADD, MaxEntScan, SpliceAI), I am not getting Mastermind annotation.

My ensembl_rest.conf is pointed to my Plugins folder and the plugin_config.txt
The Mastermind section in my plugin_config.txt I have edited as follows:

    {
      "key" => "Mastermind",
      "label" => "Mastermind",
      "helptip" => "Variants with clinical evidence cited in the medical literature reported by Mastermind Genomic Search Engine (https://www.genomenon.com/mastermind)",
      "available" => 1,
      "enabled" => 0,
      "requires_data" => 1,
      "species" => [
        "homo_sapiens"
      ],
      "section" => "Phenotype data and citations",
      "plugin_url" => "https://raw.githubusercontent.com/Ensembl/VEP_plugins/release/104/Mastermind.pm",
      "params" => [
        "/home/iroot/Programs/ensembl-vep/databases/mastermind_cited_variants_reference-2021.04.02-grch37.vcf.gz",0,1
      ]
    }

I know that the plugin is called, because when I set an invalid path to my mastermind file, I get an error `ERROR: Mastermind input file not specified or found!`. With the correct path, however, I get no error but also no output on a variant for which Mastermind output should definitely exist. I have tried the params without the `,0,1` at the end, I have tried it with `,0,1,0`, with `,"0","1"` and all permutations I could think of.

I am accessing http://127.0.0.1:3000/vep/human/hgvs/6:g.51947999G>A?content-type=application/json&refseq=1&CADD=1&vcf_string=1&hgvs=1&Mastermind=1&SpliceAI=1&MaxEntScan=1

Thanks for any suggestions you might have!
Best,
Florian

**Comment by sgiorgetti** [comment]
Closing for now. @FlorianErger pls feel free to reopen, should you have further concerns or issues.
Thanks

**Comment by FlorianErger** [comment]
> Hi @FlorianErger, I'm sorry for the late reply. We noticed there was a missing file in [ensembl_rest.conf](https://github.com/Ensembl/ensembl-rest_private/blob/release/104/grch37.rest.ensembl.org/conf/ensembl_rest.conf.j2#L237) You should make sure your local server includes this update: https://github.com/Ensembl/ensembl-rest_private/pull/99/files Let me know if you have more questions.
> 
> Best wishes, Diana

Dear @dglemos ,

thanks for the description of the problem. I unfortunately cannot access your links (error 404, private repo?) and am still facing the same issue (also on a fresh v109 installation).

Could you update the links or describe the fix?

Many thanks and best wishes,
Florian

**Comment by dglemos** [comment]
Hi @FlorianErger,
I'm sorry, the link I sent is from a private repo.
The missing config has been fixed which means you should not have the same issue. 
I will have a look at it and will let you know.

Best wishes,
Diana

**Comment by dglemos** [comment]
Mastermind is working on grch37: https://grch37.rest.ensembl.org/vep/human/id/rs699?content-type=application/json&Mastermind=1
Are you pointing to a local installation of REST?

**Comment by FlorianErger** [comment]
Yes, I was referring to the solution you kindly described in your last post. I am unable to implement it as I cannot access the links you provided.

**Comment by FlorianErger** [comment]
Just for completeness, my plugins_config.txt section on Mastermind is:

> # Mastermind
    {
      "key" => "Mastermind",
      "label" => "Mastermind",
      "helptip" => "Variants with clinical evidence cited in the medical literature reported by Mastermind Genomic Search Engine (https://www.genomenon.com/mastermind)",
      "available" => 1,
      "enabled" => 0,
      "species" => [
        "homo_sapiens"
      ],
      "params" => [
        "/opt/Ensembl/ensembl-vep/cache/Plugins/Mastermind/mastermind_cited_variants_reference-2023.01.02-grch37.vcf.gz"
      ],
      "section" => "Phenotype data and citations",
      "plugin_url" => "https://raw.githubusercontent.com/Ensembl/VEP_plugins/release/109/Mastermind.pm"
    },

My test request to my local server is:

> curl 'http://localhost:3000/vep/human/hgvs?Mastermind=1' -H 'Content-type:application/json' -H 'Accept:application/json' -X POST -d '{ "hgvs_notations" : ["6:g51947999G>A" ] }'

If I annotate directly with VEP from the command line, I get the Mastermind annotation, so the plugin itself works.

**Comment by dglemos** [comment]
Mastermind requires a file of chromosome synonyms ([vep option](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_synonyms)). The file should be tab-delimited with the primary identifier in column 1 and the synonym in column 2. You can find this file in the VEP cache, the file name is `chr_synonyms.txt`.

For Mastermind to be able to run you have to add the option `synonyms` to your VEP config. Something like this:

```
<Controller::VEP>
  fasta = {{ homo_sapiens_fasta }}
  dir    = {{ vep_cache_dir }}/
  cache_version = {{ ensembl_release }}
  cache               = 1
  failed               = 0
  sift                   = b
  polyphen         = b
  symbol            = 1
  regulatory       = 1
  check_existing = 1
  rest                   = 1
  fork                   = 0
  assembly	   = GRCh37
  biotype             = 1
  max_post_size = 300
  warning_file      = STDERR # controls VEP logging, not Catalyst
  plugin_config   = {{ vep_plugin_config }}      # as found in this dir
  dir_plugins       = {{ vep_plugin_dir }}       # checkout of https://github.com/ensembl-variation/VEP_plugins
  human_assembly    = {{ human_assembly }}
  synonyms         = path/chr_synonyms.txt
```

**Comment by FlorianErger** [comment]
Dear Diana,

perfect! That was the missing piece, the plugin now works on my local REST setup.

Thank you very much,
Best,
Florian

**Comment by dglemos** [comment]
I'm glad it's working now!

Best wishes,
Diana
