### ISSUE TITLE
SpliceAI plugin generates invalid json with gene name "NANS"

### ISSUE THREAD

**Issue by FlorianErger** [Ensembl/ensembl-rest#486]
Hello again,

I have noticed that occasionally, an invalid json is returned when querying the VEP REST API. I have narrowed down the problem to the SpliceAI plugin generating a malformed json entry for variants in the gene named "NANS". The gene name seems to be converted to the value `-nan`, which at least by Python3 requests json function and Firefox is not recognized as valid input and leads to an error when parsing.

The web-based VEP generates no errors for this query.

Example, also errors out with lifted-over coordinates in the hg38 api:
http://grch37.rest.ensembl.org/vep/human/hgvs/9:g100819192C>T?content-type=application/json&SpliceAI=1

This may have been introduced in the last update, as I have queries from a few weeks ago with the identical variant that did not give any error.
Any help would be much appreciated,
Thanks and best wishes,
Florian

**Comment by mira13** [comment]
Hello, Florian, 

This seems to be a VEP plugin issue, I have forwarded it to the VEP team. 
Will come back as they respond.


Cheers, 
Mira
