### ISSUE TITLE
Missing variant consequence

### ISSUE THREAD

**Issue by ramiromagno** [Ensembl/ensembl-rest#505]
Probably not a bug in the REST API per se, but I wasn't sure where to post this difference:

The number of variant consequences returned by [/info/variation/consequence_types](https://rest.ensembl.org/documentation/info/variation_consequence_types) is 37, yet here https://m.ensembl.org/info/genome/variation/prediction/predicted_data.html only 36 are described.

The missing one is:

`SO:0001060`, `sequence_variant`, whose description is: *A sequence_variant is a non exact copy of a sequence_feature or genome exhibiting one or more sequence_alteration*.

**Comment by helensch** [comment]
Hi @ramiromagno 

Thank you for flagging the difference.

The consequence SO:0001060 sequence_variant will be removed from the REST endpoint in a future release.
The consequence SO:0001628 intergenic_variant will be used instead.

Regards
Helen

**Comment by sgiorgetti** [comment]
Closing for now
