### ISSUE TITLE
Typo in /eqtl/stable_id/:species/:stable_id docs?

### ISSUE THREAD

**Issue by ramiromagno** [Ensembl/ensembl-rest#506]
The endpoint documentation entry https://rest.ensembl.org/documentation/info/species_id is entitled `GET eqtl/stable_id/:species/:stable_id` but in reality the example is given with `/eqtl/id/homo_sapiens/ENSG00000122435`, i.e., with `stable_id` replaced with `id`.

**Comment by sgiorgetti** [comment]
Hi @ramiromagno ,

It's a mismatch/typo, yes. Well spotted! Thanks!

**Comment by sgiorgetti** [comment]
Closing the issue: eQTL endpoints have been removed from the current release (Release 105) onwards
