### ISSUE TITLE
[Question]: Is there an API protocol for the ensembl rest service? 

### ISSUE THREAD

**Issue by LiNk-NY** [Ensembl/ensembl-rest#516]
Thank you for working on this great service!

> TL:DR
>
> Is there a JSON API protocol file for this service that is similar to those provided by others
 e.g., for cBioPortal http://www.cbioportal.org/api/api-docs ?
These type of websites (http://www.cbioportal.org/api/swagger-ui.html) make it really easy to
explore and programmatically develop clients based on the above linked protocol. 

This would reduce the amount of "tailored" functionality (across programming languages) 
by making use of programmatically generated clients based on the protocol file. 
These clients could be generated with tools such as
https://github.com/OpenAPITools/openapi-generator to create a template for the language of choice. 

Specific to our needs, we would like to work on an R client that provides full functionality based on the API protocol.
Some attempts can be seen here https://github.com/ramiromagno/ensemblr/ , https://github.com/timyates/EnsemblRest , and https://github.com/dwinter/rensembl

Thank you for your help!

Best regards,
Marcel

cc: @almahmoud

**Comment by LiNk-NY** [comment]
Hi Stefano, @sgiorgetti 

Thank you for taking the time to respond. We understand you are busy. 
Bioconductor is a major user of your service and we would be delighted to be
able to access the REST service via an API protocol. It wouldn't only benefit us
but also communities that are building software in other languages as well. 

Thanks again!

Best regards,
Marcel

**Comment by sgiorgetti** [comment]
Closing for now. Please, feel free to re-open it, should you think it worthwhile
