### ISSUE TITLE
GET vep/:species/region/:region/:allele/ endpoint dbNSFP option fails silently when improper field passed

### ISSUE THREAD

**Issue by tenzinhl** [Ensembl/ensembl-rest#544]
Hi! First off thanks for the tool, it's really cool.

## Context

For a project I'm working on the science peeps want to query multiple fields pulled from the [dbNSFP README linked from the endpoint docs](https://usf.app.box.com/s/6yi6huheisol3bhmld8bitcon1oi53pm). The issue is when multiple were entered we were getting no results. My main suspicion based on the testing below is that one of them is formatted incorrectly/deprecated, but the issue is that with hundreds of fields, it's hard to drill down and find out which one as the returned JSON result does not indicate any failures.

## The issue

Something I noticed is that when using the dbNSFP option when querying the vep_region_get endpoint: (https://rest.ensembl.org/documentation/info/vep_region_get) is that no information is added to the returned result with no indications that it failed as long as a single field passed to the endpoint is non-existent/improper.

Here's an example of a successful query I sent where dbNSFP data was successfully returned:

Query: https://rest.ensembl.org/vep/human/region/9:35075022/T/?content-type=application/json&dbNSFP=MutationTaster_pred

Result: [dbNSFP_successful_request.txt](https://github.com/Ensembl/ensembl-rest/files/9151645/dbNSFP_successful_request.txt)

Then when a dud field is appended, no extra dbNSFP data is included at all:

Query: https://rest.ensembl.org/vep/human/region/9:35075022/T/?content-type=application/json&dbNSFP=MutationTaster_pred,fakefield

Result: [dbNSFP_failed_request.txt](https://github.com/Ensembl/ensembl-rest/files/9151637/dbNSFP_failed_request.txt)

There's a few issues I have with this behavior:
1. dbNSFP information is all or nothing. If a single field is bad, it will cause none to be included in the final response
2. It fails silently. The returned JSON will have no indication that the dbNSFP portion of the query failed. This makes it impossible to distinguish a query where the dbNSFP fields were improper from a query where the specified variant just didn't have any associated dbNSFP information for the queried fields.

## Desired Outcome

I think ideally the endpoint would make a note somehow that the dbNSFP query failed, and if it's available note which fields were not found.

## Workarounds

By reading through the [dbNSFP plugin details linked from the endpoint docs](https://raw.githubusercontent.com/ensembl-variation/VEP_plugins/master/dbNSFP.pm) I found that "ALL" can be used as an endpoint option to query everything. This worked for our situation since we already wanted to query so many fields, and could then just filter out the unneeded ones.

**Comment by nuno-agostinho** [comment]
Hi @tenzinhl,

We have now fixed this for release 110. When asking for invalid fields, the dbNSFP plugin will return those invalid fields with the value `invalid_field`. This way, you get data for the valid fields and you know which ones are invalid.

Thanks for opening this issue and sorry for the delay in answering/fixing.

Best,
Nuno

PS: @sgiorgetti Could you please close this ticket? Thanks!
