### ISSUE TITLE
Really long latency on `Lookup/symbol`

### ISSUE THREAD

**Issue by noamteyssier** [Ensembl/ensembl-rest#561]
Been noticing this the past week or two. Not just on this endpoint but I can reproduce very consistently with this one. 

Here's the example provided on the REST API.
```
curl 'https://rest.ensembl.org/lookup/symbol/homo_sapiens' -H 'Content-type:application/json' \
    -H 'Accept:application/json' -X POST -d '{ "symbols" : ["BRCA2", "BRAF" ] }'
```
Timing takes about 1 minute or will timeout no matter what computer or server I query from.

**Comment by sgiorgetti** [comment]
Hello @noamteyssier  - apologies for this very belated reply.
We monitored - and I guess fixed something behind the scene - the behaviour lately and your query takes now less than 1s to run from outside EBI network.

Hope this helps. I am closing the issue for now.
Any further questions, please do not hesitate to ask here or directly via any of our EnsEMBL channels at the following link http://www.ensembl.org/info/about/contact/index.html
