### ISSUE TITLE
GET overlap/ endpoints missing exons at edge of region

### ISSUE THREAD

**Issue by feliciazhang** [Ensembl/ensembl-rest#588]
Hello! Running into a possible inclusive/exclusive region edge case with the `GET overlap/id/:id` and `GET overlap/region/:species/:region` endpoints. When fetching features from a gene ID/region where there is a exon at the start of the specified region that has a length of 1, that exon is not included in the response as expected.

For example:

Endpoint `overlap/id/Pf3D7_0807000` with parameters `feature=gene;feature=transcript;feature=cds;feature=exon` and content type `"text/x-gff3"` has the response below where the exon `CAX64101-1` with start and end at 370784 is missing. Per the exon table on the [Ensembl site](https://protists.ensembl.org/Plasmodium_falciparum/Transcript/Exons?db=core;g=PF3D7_0807000;r=8:370784-372623;t=CAX64101) I would expect this exon to be included in this region specified by the gene. The same result occurs when using the `/region/` version of the endpoint with the gene's region `overlap/region/plasmodium_falciparum/8:370784-372623`. Interestingly, CDS features at that same 370784-370784 position are included in the response when CDS is added to the feature parameters.

```
##gff-version 3
##sequence-region   8 370784 372623
8	ena	gene	370784	372623	.	+	.	ID=gene:PF3D7_0807000;assembly_name=ASM276v2;biotype=protein_coding;description=gas41 homologue%2C putative;gene_id=PF3D7_0807000;logic_name=ena
8	ena	mRNA	370784	372623	.	+	.	ID=transcript:CAX64101;Parent=gene:PF3D7_0807000;assembly_name=ASM276v2;biotype=protein_coding;logic_name=ena;transcript_id=CAX64101
8	ena	exon	370911	370987	.	+	.	Name=CAX64101-2;Parent=transcript:CAX64101;assembly_name=ASM276v2;constitutive=1;ensembl_end_phase=0;ensembl_phase=1;exon_id=CAX64101-2;rank=2
8	ena	exon	371150	371282	.	+	.	Name=CAX64101-3;Parent=transcript:CAX64101;assembly_name=ASM276v2;constitutive=1;ensembl_end_phase=1;ensembl_phase=0;exon_id=CAX64101-3;rank=3
8	ena	exon	371493	371611	.	+	.	Name=CAX64101-4;Parent=transcript:CAX64101;assembly_name=ASM276v2;constitutive=1;ensembl_end_phase=0;ensembl_phase=1;exon_id=CAX64101-4;rank=4
8	ena	exon	371735	371785	.	+	.	Name=CAX64101-5;Parent=transcript:CAX64101;assembly_name=ASM276v2;constitutive=1;ensembl_end_phase=0;ensembl_phase=0;exon_id=CAX64101-5;rank=5
8	ena	exon	371920	372022	.	+	.	Name=CAX64101-6;Parent=transcript:CAX64101;assembly_name=ASM276v2;constitutive=1;ensembl_end_phase=1;ensembl_phase=0;exon_id=CAX64101-6;rank=6
8	ena	exon	372137	372252	.	+	.	Name=CAX64101-7;Parent=transcript:CAX64101;assembly_name=ASM276v2;constitutive=1;ensembl_end_phase=0;ensembl_phase=1;exon_id=CAX64101-7;rank=7
8	ena	exon	372424	372454	.	+	.	Name=CAX64101-8;Parent=transcript:CAX64101;assembly_name=ASM276v2;constitutive=1;ensembl_end_phase=1;ensembl_phase=0;exon_id=CAX64101-8;rank=8
8	ena	exon	372586	372623	.	+	.	Name=CAX64101-9;Parent=transcript:CAX64101;assembly_name=ASM276v2;constitutive=1;ensembl_end_phase=0;ensembl_phase=1;exon_id=CAX64101-9;rank=9
```
Adjusting the region to extend the start value by 1 (`overlap/region/plasmodium_falciparum/8:370783-372623`) does include the missing `CAX64101-1` exon.

**Comment by sgiorgetti** [comment]
Closing for now, as nothing has come up so far.
