### ISSUE TITLE
REST API for VEP is down for version 105

### ISSUE THREAD

**Issue by Z-Zen** [Ensembl/ensembl-rest#642]
Hello,

It seems that the REST API is down for VEP version 105:

```bash
> curl 'https://dec2021.rest.ensembl.org/vep/homo_sapiens/region' -H 'Content-type:application/json' \
-H 'Accept:application/json' -X POST -d '{ "variants" : ["21  26960070  rs116645811 G A . . .", "21  26965148  rs1135638 G A . . ." ] }'

{"error":"ERROR: Cache directory /nfs/public/release/ensweb-data/tools/www/e108/vep/cache///homo_sapiens not found"}
```

Is there an on-going maintenance?

Thank you

**Comment by sgiorgetti** [comment]
Hello @Z-Zen  - thanks for flagging this up.
Apparently, we have a problem with the VEP cache, and we are looking into it now.

**Comment by sgiorgetti** [comment]
Hello again @Z-Zen - the REST instance for e!105 seems to be back among the living again!
Closing this for now. Feel free to re-open it, if you feel like so. Cheers

**Comment by sgiorgetti** [comment]
Hello @Z-Zen - thanks for flagging this up, and apologies for the not-so-prompt reply.
I've flagged this up to our Web team, and they are going to fix it ... again ... hopefully soon.

**Comment by sgiorgetti** [comment]
@Z-Zen - Fixed, apparently. Thanks for your patience
