### ISSUE TITLE
REST API for VEP is down for version 105, again

### ISSUE THREAD

**Issue by Z-Zen** [Ensembl/ensembl-rest#652]
Hi,

The issue happened again as the one mentioned below. Can you please check on your end?

Thanks!

_Originally posted by @Z-Zen in https://github.com/Ensembl/ensembl-rest/issues/642#issue-2273107161

**Comment by sgiorgetti** [comment]
Hello @Z-Zen - thanks for flagging this up, and apologies for the not-so-prompt reply.
I've flagged this up to our Web team, and they are going to fix it ... again ... hopefully soon.
